---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "memex-migration-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "memex-migration"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  MEMEX_HOST: "{{ .Values.config.memex_migration.MEMEX_HOST }}"
  MEMEX_PORT: "{{ .Values.config.memex_migration.MEMEX_PORT }}"
  MEMEX_USERNAME: "{{ .Values.config.memex_migration.MEMEX_USERNAME }}"
  MEMEX_JDBCCONNECTIONSTRING: "{{ .Values.config.memex_migration.MEMEX_JDBCCONNECTIONSTRING }}"
  MEMEX_DATABASENAME: "{{ .Values.config.memex_migration.MEMEX_DATABASENAME }}"
