using MeshWeaver.AI.Delegation;
using MeshWeaver.AI.Persistence;
using MeshWeaver.Layout;
using Microsoft.Extensions.AI;

namespace MeshWeaver.AI;

public interface IAgentChat
{
    void SetContext(AgentContext? applicationContext);

    /// <summary>Sets the currently selected agent by name.</summary>
    /// <param name="agentName">The name/ID of the agent to use</param>
    void SetSelectedAgent(string? agentName);

    Task ResumeAsync(ChatConversation conversation);

    /// <summary>
    /// Returns an ordered list of agents for the current context.
    /// The first agent is the recommended default for the current context.
    /// Order: context-matching agents first, then default agents by path depth, then others.
    /// </summary>
    Task<IReadOnlyList<AgentDisplayInfo>> GetOrderedAgentsAsync();

    /// <summary>Sends chat messages and returns the response.</summary>
    /// <param name="messages">The sequence of chat messages to send.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The response messages generated by the client.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="messages"/> is <see langword="null"/>.</exception>
    /// <related type="Article" href="https://learn.microsoft.com/dotnet/ai/microsoft-extensions-ai#request-a-chat-response">Request a chat response.</related>
    IAsyncEnumerable<ChatMessage> GetResponseAsync(
        IReadOnlyCollection<ChatMessage> messages,
        CancellationToken cancellationToken = default);

    /// <summary>Sends chat messages and streams the response.</summary>
    /// <param name="messages">The sequence of chat messages to send.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>The response messages generated by the client.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="messages"/> is <see langword="null"/>.</exception>
    /// <related type="Article" href="https://learn.microsoft.com/dotnet/ai/microsoft-extensions-ai#request-a-streaming-chat-response">Request a streaming chat response.</related>
    IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IReadOnlyCollection<ChatMessage> messages,
        CancellationToken cancellationToken = default);

    /// <summary>Sets the current thread ID for conversation persistence.</summary>
    /// <param name="threadId">The thread identifier</param>
    void SetThreadId(string threadId);

    /// <summary>
    /// Sets the persistent thread ID for server-side conversation history.
    /// When set and using a persistent factory, the agent session links to this server-managed thread.
    /// </summary>
    void SetPersistentThreadId(string? persistentId) { }

    /// <summary>
    /// Sets attachment paths whose content will be loaded and included in the next message.
    /// Attachments are cleared after use.
    /// </summary>
    void SetAttachments(IReadOnlyList<string>? paths) { }

    /// <summary>Displays a layout area in the chat as a visual component.</summary>
    /// <param name="layoutAreaControl">The layout area control</param>
    void DisplayLayoutArea(LayoutAreaControl layoutAreaControl);

    /// <summary>
    /// Requests a handoff to a target agent. The target agent takes over the shared thread.
    /// </summary>
    void RequestHandoff(HandoffRequest request) { }

    AgentContext? Context { get; }

    /// <summary>
    /// Current execution context (thread path, response message ID).
    /// Set by ThreadExecution during streaming, used by delegation tools for sub-thread persistence.
    /// </summary>
    ThreadExecutionContext? ExecutionContext => null;

    /// <summary>
    /// Live stream of delegation lifecycle events
    /// (Dispatched → Active → Terminal). Single source of truth for
    /// "which sub-threads is this chat session waiting on?" The cancel
    /// watcher subscribes here and maintains its own active-set; the
    /// tool-call stamper writes the path onto the parent's tool-call entry
    /// on the Dispatched event.
    /// </summary>
    IObservable<DelegationEvent> Delegations
        => System.Reactive.Linq.Observable.Empty<DelegationEvent>();

    /// <summary>
    /// Callback to forward tool call entries from sub-threads to the parent's tool call log.
    /// Called during delegation polling when new tool calls are detected on sub-threads.
    /// </summary>
    Action<ToolCallEntry>? ForwardToolCall { get => null; set { } }

    /// <summary>
    /// Callback to forward node change entries from MeshOperations (Create/Update/Patch).
    /// Set by ThreadExecution, invoked by MeshPlugin when nodes are modified.
    /// Tracks path + version before/after for document change auditing per thread message.
    /// </summary>
    Action<NodeChangeEntry>? ForwardNodeChange { get => null; set { } }

}
