using System.Collections.Immutable;
using System.Text.Json;
using System.Text.Json.Serialization;
using MeshWeaver.Layout;
using MeshWeaver.Messaging;
using MeshWeaver.ShortGuid;

namespace MeshWeaver.AI;


/// <summary>
/// Tracks execution context for delegation sub-thread creation.
/// Set by ThreadExecution, consumed by delegation tools.
/// </summary>
public record ThreadExecutionContext
{
    /// <summary>Thread path where the current execution is running.</summary>
    public required string ThreadPath { get; init; }

    /// <summary>Response message ID within the thread.</summary>
    public required string ResponseMessageId { get; init; }

    /// <summary>
    /// The original content node path (e.g., "PartnerRe/AiConsulting").
    /// Propagated through all delegation levels so sub-threads always
    /// know the root context for namespace resolution and agent initialization.
    /// </summary>
    public string? ContextPath { get; init; }

    /// <summary>
    /// The user's AccessContext captured from the original delivery.
    /// Used to propagate user identity through delegation chains.
    /// </summary>
    public AccessContext? UserAccessContext { get; init; }
}

/// <summary>
/// Control-plane intent payload for <see cref="WorkspaceThreadExtensions.ResubmitMessage"/>.
/// Written into <see cref="Thread.RequestedResubmit"/> via a single-field
/// <c>stream.Update</c> from any hub (own or cross-hub — single-field patches
/// are RFC-7396-merge-safe so the framework's <c>UpdateRemote</c> staleness
/// can't double-write). The owning thread hub's resubmit watcher consumes the
/// intent, applies the truncate + re-queue mutations against its own
/// workspace, and clears the field atomically in the same update.
/// </summary>
public sealed record ResubmitIntent(
    string UserMessageId,
    string? NewUserText,
    string? AgentName,
    string? ModelName,
    DateTime RequestedAt);

/// <summary>
/// Control-plane intent payload for
/// <see cref="WorkspaceThreadExtensions.RecordSubmissionFailure"/>. The caller
/// patches one entry into <see cref="Thread.PendingFailures"/> via a
/// single-key <c>stream.Update</c> (RFC-7396 dict-SetItem is merge-safe).
/// The owning thread hub's failure watcher creates the error cell, appends
/// it to <see cref="Thread.Messages"/>, and removes the entry atomically.
///
/// <para><see cref="ErrorCellId"/> is pre-generated by the caller so a
/// watcher re-fire (e.g. from a stream replay) cannot create a duplicate
/// error cell — the satellite create is idempotent on the cell id.</para>
/// </summary>
public sealed record FailureRecord(
    string UserText,
    string ErrorMessage,
    string ErrorCellId,
    DateTime RequestedAt);

/// <summary>
/// Explicit lifecycle state for a thread's overall execution round. Replaces
/// the binary <see cref="Thread.IsExecuting"/> flag with named states so the
/// GUI can render distinct progress indicators and so test assertions can
/// pin the transition graph.
///
/// <para>State graph (one execution round):
/// <c>Idle → StartingExecution → Executing → Completing → Idle</c>. The
/// thread can only re-enter <see cref="StartingExecution"/> from
/// <see cref="Idle"/>; cancellation/error doesn't fork the graph — the
/// terminal status lands on the response cell (<see cref="ThreadMessageStatus"/>),
/// while the thread always flows through <see cref="Completing"/> back to
/// <see cref="Idle"/>.</para>
/// </summary>
public enum ThreadExecutionStatus
{
    /// <summary>No round in flight. PendingUserMessages may still hold queued input —
    /// the submission watcher will dispatch a new round when it observes this state.</summary>
    Idle = 0,

    /// <summary>The <c>_Exec</c> hub claimed the round: draining
    /// <see cref="Thread.PendingUserMessages"/> into <see cref="Thread.Messages"/>,
    /// materialising user satellite cells, allocating the response cell. No
    /// agent tokens yet.</summary>
    StartingExecution,

    /// <summary>Agent is streaming into the active response cell. The
    /// <c>check_inbox</c> tool may drain newly-arrived pending entries into
    /// <see cref="Thread.Messages"/> mid-stream; the same response cell keeps
    /// streaming.</summary>
    Executing,

    /// <summary>Stream loop has exited (normal / cancel / error). End-of-round
    /// drain runs (any unread pending entries flush into Messages, marked
    /// ingested so the watcher doesn't immediately re-dispatch), then the
    /// response cell's terminal status is committed and the thread transitions
    /// back to <see cref="Idle"/>.</summary>
    Completing,

    /// <summary>User-marked terminal state — the thread is finished and
    /// hidden from default catalogs (queries default to
    /// <c>-content.status:Done</c>). A new <c>SubmitMessageRequest</c>
    /// implicitly transitions back to <see cref="Idle"/> so the user can
    /// reopen a conversation by typing.</summary>
    Done
}

/// <summary>
/// Lifecycle state of a single ThreadMessage cell. Replaces magic-string text
/// markers like trailing "*Cancelled*" / "*Error: ...*" with an explicit
/// per-cell state machine.
///
/// User cells: created at <see cref="Submitted"/> on dispatch (the queued period
/// lives at the thread level via <see cref="Thread.PendingUserMessages"/> —
/// the cell doesn't exist until ingestion).
///
/// Assistant cells: created at <see cref="Streaming"/> on round start, transition
/// to one of <see cref="Completed"/>, <see cref="Cancelled"/>, or <see cref="Error"/>
/// when the streaming loop exits.
///
/// Pre-existing persisted cells without a Status field default to <see cref="Completed"/>
/// (treated as stable history).
/// </summary>
public enum ThreadMessageStatus
{
    /// <summary>User cell appended to the thread queue, satellite not yet materialized.
    /// In practice cells almost never carry this value (the queue lives on the thread,
    /// not the cell) — included for completeness so external materializers can use it.</summary>
    Queued,

    /// <summary>User cell materialized into a round (the round may be running or done).</summary>
    Submitted,

    /// <summary>Assistant cell currently being generated — streaming loop active.</summary>
    Streaming,

    /// <summary>Cell's turn finished successfully.</summary>
    Completed,

    /// <summary>Cell's turn was cancelled mid-stream (ESC / Stop). Partial text preserved.</summary>
    Cancelled,

    /// <summary>Cell's turn failed with an error. Error message in <see cref="ThreadMessage.Text"/>.</summary>
    Error
}

/// <summary>
/// Defines the type of a thread message for rendering purposes.
/// </summary>
public enum ThreadMessageType
{
    /// <summary>
    /// User is currently editing this message (not yet submitted).
    /// Rendered with MarkdownEditorControl.
    /// </summary>
    EditingPrompt,

    /// <summary>
    /// Submitted user message.
    /// Rendered with MarkdownControl (readonly).
    /// </summary>
    ExecutedInput,

    /// <summary>
    /// Assistant/agent response message.
    /// Rendered with MarkdownControl (readonly).
    /// </summary>
    AgentResponse
}

/// <summary>
/// Content stored in Thread MeshNodes.
/// Threads are stored as MeshNodes with nodeType="Thread".
/// Title is stored in MeshNode.Name, LastModified tracks activity.
/// Messages are stored as child MeshNodes with nodeType="ThreadMessage".
/// </summary>
public record Thread
{
    /// <summary>
    /// Serialized AgentSession state for resuming conversations.
    /// </summary>
    public JsonElement? SessionState { get; init; }

    /// <summary>
    /// Child mesh nodes. Thread controls and keeps up to date.
    /// </summary>
    public ImmutableList<string> Messages { get; init; } = [];

    /// <summary>
    /// All user-message ids in <see cref="Messages"/>, in order. The client appends to both
    /// <see cref="Messages"/> and this list on submit, so the server watcher can identify
    /// user messages without cross-hub child-cell lookups.
    /// </summary>
    public ImmutableList<string> UserMessageIds { get; init; } = [];

    /// <summary>
    /// Ids of user messages already committed to an execution round (past or current).
    /// A user message id appearing in <see cref="UserMessageIds"/> but NOT in this set is "queued"
    /// and will be ingested by the server watcher when the next round opens.
    /// Multiple queued messages are ingested together into a single round / single output cell.
    /// </summary>
    public ImmutableList<string> IngestedMessageIds { get; init; } = [];

    /// <summary>
    /// Azure AI Foundry persistent thread ID. When set, conversation history is server-managed.
    /// </summary>
    public string? PersistentThreadId { get; init; }

    /// <summary>
    /// The provider type that created this thread (e.g., "AzureFoundryPersistent").
    /// Determines whether server-side history is available.
    /// </summary>
    public string? ProviderType { get; init; }

    /// <summary>
    /// The user ID who created this thread.
    /// Used to filter "my threads" across all partitions.
    /// </summary>
    public string? CreatedBy { get; init; }

    /// <summary>
    /// The thread's main output — the dedicated summary the agent produces at
    /// the end of execution before returning. For sub-threads spawned via
    /// <c>delegate_to_agent</c>, this is the value returned to the parent
    /// agent as the tool-call result. Written by <c>ExecuteMessageAsync</c> at
    /// the Completed terminal state (copies the last assistant message's text),
    /// and the agent itself may overwrite it via a dedicated tool to provide
    /// a tighter summary than the verbose chat response.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// Explicit state machine for the round currently in flight. See
    /// <see cref="ThreadExecutionStatus"/> for the transition graph. The
    /// submission watcher fires when <see cref="Status"/> is
    /// <see cref="ThreadExecutionStatus.Idle"/> and
    /// <see cref="PendingUserMessages"/> is non-empty.
    /// </summary>
    public ThreadExecutionStatus Status { get; init; } = ThreadExecutionStatus.Idle;

    /// <summary>
    /// Backwards-compatible boolean shorthand for "round in flight". True for
    /// <see cref="ThreadExecutionStatus.StartingExecution"/>,
    /// <see cref="ThreadExecutionStatus.Executing"/>, and
    /// <see cref="ThreadExecutionStatus.Completing"/>. Idle + Done are not
    /// executing — Done is the user-marked terminal state.
    /// New callsites should read <see cref="Status"/> directly to pick a
    /// specific transition.
    /// </summary>
    [JsonIgnore]
    public bool IsExecuting
        => Status is ThreadExecutionStatus.StartingExecution
                  or ThreadExecutionStatus.Executing
                  or ThreadExecutionStatus.Completing;

    /// <summary>
    /// Current execution activity description (e.g., "Calling search_nodes...", "Delegating to Navigator...").
    /// Updated during streaming when tool calls or delegations occur.
    /// </summary>
    public string? ExecutionStatus { get; init; }

    /// <summary>
    /// The ID of the response message currently being generated. The full
    /// response path is always <c>{threadPath}/{ActiveMessageId}</c> — every
    /// downstream actor (_Exec streaming loop, parent's delegation watcher,
    /// cancellation watcher, GUI status bar) derives the path that way.
    /// Single source of truth for "where is the agent streaming right now";
    /// no separate path-property to keep in sync with the id.
    /// </summary>
    public string? ActiveMessageId { get; init; }

    /// <summary>
    /// Total tokens used in the current execution (input + output).
    /// </summary>
    public int TokensUsed { get; init; }

    /// <summary>
    /// When the current execution started. Used to show elapsed time.
    /// </summary>
    public DateTime? ExecutionStartedAt { get; init; }

    /// <summary>
    /// Wall clock of the most recent "the agent is still making progress"
    /// signal — streaming text deltas, tool-call activity, status changes.
    /// Written atomically with those events in the OWNING thread hub's
    /// action block (no extra writes, no race). Read by the parent thread
    /// hub's heartbeat watcher: if <c>IsExecuting=true</c> AND
    /// <c>(now - LastActivityAt) &gt; HeartbeatTimeout</c> (with a 60 s
    /// cold-start grace measured from <see cref="ExecutionStartedAt"/>),
    /// the watcher flips <see cref="RequestedCancellationAt"/> on this
    /// sub-thread — the same primitive the GUI Stop button uses. Replaces
    /// the hard 5-minute watchdog in <c>ExecuteDelegationAsync</c>.
    /// </summary>
    public DateTime? LastActivityAt { get; init; }

    /// <summary>
    /// Per-thread override of the framework-default heartbeat timeout
    /// (30 s). Set by an agent that legitimately makes slow progress
    /// (e.g. non-streaming chat client with long single-shot completions).
    /// Null → use default. The 60 s cold-start grace is applied
    /// regardless, so the value can be aggressive without false-positives
    /// on cold start.
    /// </summary>
    public TimeSpan? HeartbeatTimeout { get; init; }

    /// <summary>
    /// User requested cancellation of the in-flight round. The thread hub's
    /// cancel watcher observes its own thread node and, when
    /// <c>RequestedCancellationAt &gt; ExecutionStartedAt</c>, cancels the
    /// stored CTS and propagates the same flip onto every active delegation
    /// sub-thread.
    ///
    /// <para><b>Stream-update only — never a MeshThread.RequestedCancellationAt flip.</b> The
    /// owning thread hub serialises writes on its action block, so racing
    /// flips collapse into one observed transition. See
    /// [RequestViaStreamUpdate.md] for the rule.</para>
    /// </summary>
    public DateTime? RequestedCancellationAt { get; init; }

    /// <summary>
    /// Control-plane intent: a non-null value signals an external caller
    /// (typically the chat UI) wants the thread truncated after a user
    /// message and re-ingested with optional new text/agent/model. The
    /// thread hub's resubmit watcher consumes the intent, applies the
    /// mutation, and clears the field atomically in the same
    /// <c>stream.Update</c>. See <see cref="ResubmitIntent"/>.
    /// </summary>
    public ResubmitIntent? RequestedResubmit { get; init; }

    /// <summary>
    /// Control-plane intent: a non-null value signals an external caller
    /// wants <see cref="Messages"/> truncated at this id (exclusive — drops
    /// this id and everything after). The thread hub's delete watcher
    /// applies the truncation and clears the field atomically.
    /// </summary>
    public string? RequestedDeleteFromMessageId { get; init; }

    /// <summary>
    /// Control-plane intent: failure records reported by submitters that
    /// errored before the thread hub's submission watcher could ingest the
    /// message. Each entry triggers the thread hub's failure watcher to
    /// create an error cell and update <see cref="Messages"/>. Dict-SetItem
    /// is RFC-7396-merge-safe so cross-hub patches don't race. See
    /// <see cref="FailureRecord"/>.
    /// </summary>
    public ImmutableDictionary<string, FailureRecord> PendingFailures { get; init; }
        = ImmutableDictionary<string, FailureRecord>.Empty;

    /// <summary>
    /// Pending user message text — set at thread creation to auto-start execution.
    /// When the thread grain activates and sees this, it immediately starts streaming.
    /// Cleared after execution starts.
    /// Legacy: still used by the auto-execute-on-creation path. New submissions
    /// from the GUI populate <see cref="PendingUserMessages"/> instead.
    /// </summary>
    public string? PendingUserMessage { get; init; }

    /// <summary>
    /// User messages submitted by the client but not yet ingested into a round.
    /// Keyed by user message id. The server-side submission watcher creates
    /// satellite ThreadMessage cells from these entries and clears them once
    /// the round is dispatched. Lets us do the entire submission as a single
    /// atomic <c>stream.Update</c> on this thread node — no separate
    /// CreateNodeRequest, no ThreadInput.AppendUserInput.
    /// </summary>
    public ImmutableDictionary<string, ThreadMessage> PendingUserMessages { get; init; }
        = ImmutableDictionary<string, ThreadMessage>.Empty;

    /// <summary>Agent name for pending execution.</summary>
    public string? PendingAgentName { get; init; }

    /// <summary>Model name for pending execution.</summary>
    public string? PendingModelName { get; init; }

    /// <summary>
    /// Agent name selected on this thread (sticky across reloads). The
    /// chat picker reads this on resume so the user's choice survives a
    /// page refresh / Aspire restart. Updated whenever the user picks a
    /// different agent (dropdown or <c>/agent</c> command). Null on a new
    /// thread → the chat falls back to the orchestrator default.
    /// </summary>
    public string? SelectedAgentName { get; init; }

    /// <summary>
    /// Model id selected on this thread (sticky across reloads). Same
    /// resume semantics as <see cref="SelectedAgentName"/>. Null →
    /// inherit the selected agent's PreferredModel (or first available).
    /// </summary>
    public string? SelectedModelName { get; init; }

    /// <summary>Context path for pending execution.</summary>
    public string? PendingContextPath { get; init; }

    /// <summary>Attachments for pending execution.</summary>
    public IReadOnlyList<string>? PendingAttachments { get; init; }

    [JsonIgnore]
    public string? StreamingText { get; init; }

    [JsonIgnore]
    public ImmutableList<ToolCallEntry>? StreamingToolCalls { get; init; }

}

/// <summary>
/// Extension methods for Thread message operations.
/// </summary>
public static class ThreadMessageExtensions
{
    /// <summary>
    /// Converts ThreadMessage collection to Microsoft.Extensions.AI.ChatMessage format.
    /// </summary>
    public static List<Microsoft.Extensions.AI.ChatMessage> ToChatMessages(this IEnumerable<ThreadMessage> messages)
    {
        return messages
            .Where(msg => msg.Type != ThreadMessageType.EditingPrompt)
            .Select(msg => new Microsoft.Extensions.AI.ChatMessage(
                new Microsoft.Extensions.AI.ChatRole(msg.Role),
                msg.Text)
            {
                AuthorName = msg.AuthorName
            }).ToList();
    }
}

/// <summary>
/// Represents a single message in a thread conversation.
/// Stored as content of child MeshNodes under a Thread node.
/// </summary>
public record ThreadMessage
{
    /// <summary>
    /// The role of the message sender: "user", "assistant", or "system".
    /// </summary>
    public required string Role { get; init; }

    /// <summary>
    /// Optional author name for multi-agent conversations.
    /// </summary>
    public string? AuthorName { get; init; }

    /// <summary>
    /// The text content of the message.
    /// </summary>
    public required string Text { get; init; }

    /// <summary>
    /// Dedicated summary the agent produces at end-of-stream — a tighter
    /// one-or-two-sentence distillation of <see cref="Text"/>. Written by
    /// <c>ExecuteMessageAsync</c> in the same stream.Update cycle as the
    /// final <see cref="ThreadMessageStatus.Completed"/> + thread-level
    /// <see cref="Thread.Summary"/> flip. For sub-threads spawned via
    /// <c>delegate_to_agent</c>, this is what the parent's tool-call result
    /// resolves to — never the raw verbose <see cref="Text"/>.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// When the message was created.
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// The type of this message for rendering purposes.
    /// Defaults to ExecutedInput for backward compatibility.
    /// </summary>
    public ThreadMessageType Type { get; init; } = ThreadMessageType.ExecutedInput;

    /// <summary>
    /// Lifecycle state of this cell. Default <see cref="ThreadMessageStatus.Completed"/>
    /// keeps pre-existing persisted cells (loaded without a Status field) treated as
    /// stable history. New cells set Status explicitly on creation:
    /// user → Submitted, assistant → Streaming.
    /// </summary>
    public ThreadMessageStatus Status { get; init; } = ThreadMessageStatus.Completed;

    /// <summary>
    /// The name of the agent that generated this response (for AgentResponse messages).
    /// </summary>
    public string? AgentName { get; init; }

    /// <summary>
    /// The model used to generate this response (for AgentResponse messages).
    /// </summary>
    public string? ModelName { get; init; }

    /// <summary>
    /// The user who created this message. Set from the delivery's AccessContext.
    /// </summary>
    public string? CreatedBy { get; init; }

    /// <summary>
    /// Completed tool calls from this message's execution.
    /// Populated when execution finishes, used for post-execution inspection.
    /// </summary>
    public ImmutableList<ToolCallEntry> ToolCalls { get; init; } = [];

    /// <summary>
    /// Nodes created or updated during this message's execution.
    /// Tracks path and version before/after so the UI can show
    /// which documents were written and the version delta.
    /// </summary>
    public ImmutableList<NodeChangeEntry> UpdatedNodes { get; init; } = [];

    /// <summary>
    /// For user messages: the context path (e.g. the current nav context) to pass to the agent.
    /// Null for assistant messages.
    /// </summary>
    public string? ContextPath { get; init; }

    /// <summary>
    /// For user messages: paths referenced as @-attachments.
    /// Null/empty for assistant messages.
    /// </summary>
    public IReadOnlyList<string>? Attachments { get; init; }

    /// <summary>
    /// Signals that this user cell was updated as a resubmit.
    /// The server watcher truncates the thread after this id and re-ingests.
    /// </summary>
    public bool IsResubmit { get; init; }

    /// <summary>
    /// Token usage reported by the model provider. Populated for AgentResponse cells
    /// when the streaming finishes. Null while streaming or when the provider didn't
    /// report usage (e.g., some local models). Sum of <see cref="InputTokens"/> +
    /// <see cref="OutputTokens"/> may differ from <see cref="TotalTokens"/> if the
    /// provider includes cached / reasoning tokens.
    /// </summary>
    public int? InputTokens { get; init; }
    public int? OutputTokens { get; init; }
    public int? TotalTokens { get; init; }

    /// <summary>
    /// Wall-clock time when the assistant response finished streaming. Null while
    /// streaming. <c>CompletedAt - Timestamp</c> is the per-message duration.
    /// </summary>
    public DateTime? CompletedAt { get; init; }
}
