using Azure.Provisioning.AppContainers;
using Azure.Provisioning.ApplicationInsights;
using Microsoft.Extensions.Hosting;

var builder = DistributedApplication.CreateBuilder(args);

// Mode: "local" (default), "test", "prod", "monolith"
// Pass as command line argument: dotnet run -- --mode test
//
// Mode matrix:
//   Mode        | PostgreSQL              | Blob Storage | Orleans    | Portal Name
//   ----------- | ----------------------- | ------------ | ---------- | -----------
//   local       | Docker pgvector (memex) | Emulated     | Emulated   | memex-local
//   test        | Azure (memex-test)      | Azure        | Azure      | memex-test
//   prod        | Azure (memex)           | Azure        | Azure      | memex-prod
//   monolith    | FileSystem (standalone) | —            | —          | memex-monolith
//
// Secrets: set locally via `dotnet user-secrets`, in CI/CD via GitHub secrets.
// UserSecretsId: memex-apphost (see Memex.AppHost.csproj)
//
// Required user-secrets for distributed modes:
//   Parameters:azure-foundry-key
//   Parameters:embedding-endpoint
//   Parameters:embedding-key
//   Parameters:embedding-model
//   Parameters:microsoft-client-id
//   Parameters:microsoft-client-secret
//   Parameters:microsoft-tenant-id
//   Parameters:linkedin-client-secret          (LinkedIn publishing — client id is inlined below)
//
// For local-test/local-prod, also set the connection string to the Azure PostgreSQL:
//   ConnectionStrings:memex  (Azure PostgreSQL, bypassing provisioning)
// Blob Storage uses RunAsExisting with Azure Identity (az login) — no secrets needed.

var mode = builder.Configuration["mode"]?.ToLowerInvariant() ?? "local";

if (mode == "monolith")
{
    // Standalone portal without Orleans or external infrastructure
    builder
        .AddProject<Projects.Memex_Portal_Monolith>("memex-monolith")
        .WithEnvironment("ASPNETCORE_ENVIRONMENT", "Development")
        .WithExternalHttpEndpoints();
    builder.Build().Run();
    return;
}

// --- Self-host targets: artifacts GENERATED by Aspire publishers from the reusable
//     AddMemex model (no hand-authored compose/Helm). One model → many outputs:
//       aspire publish --publisher docker-compose -o deploy/compose   (mode=compose / compose-ha)
//       aspire publish --publisher kubernetes     -o deploy/helm       (mode=kubernetes / kubernetes-ha)
//     Azure-free: Postgres (pgvector container) + filesystem backend on volumes + the portal-ai
//     image. HA flips Orleans clustering to ADO.NET-Postgres (the proxy + RWX volume are
//     finalized in the generated baseline / chart values). ---
if (mode is "compose" or "compose-ha" or "kubernetes" or "kubernetes-ha")
{
    var ha = mode.EndsWith("-ha", StringComparison.Ordinal);

    if (mode.StartsWith("compose", StringComparison.Ordinal))
        builder.AddDockerComposeEnvironment("self-host");
    else
        builder.AddKubernetesEnvironment("k8s")
            .WithHelm(helm => helm
                .WithChartName("memex")
                .WithChartDescription("MeshWeaver Memex portal — Azure-free Kubernetes self-host."));

    builder.AddMemex("memex", o => o
        .WithBackend("Filesystem")
        // Real, Postgres-backed cluster membership (never Localhost in prod). Works for a single
        // silo or HA; `ha` only drives replica count, not the membership provider.
        .WithOrleansClustering("AdoNet")
        .WithAiClis()
        .WithImage(tag: builder.Configuration["Parameters:image-tag"])
        .WithMasterKey(builder.Configuration["Parameters:key-protection-master-key"]));

    builder.Build().Run();
    return;
}

// --- Shared Parameters (linked to GitHub secrets; locally via `dotnet user-secrets`) ---

// LLM API key (single Azure Foundry key for both Anthropic and OpenAI endpoints)
var azureFoundryKey = builder.AddParameter("azure-foundry-key", secret: true);

// Authentication (Microsoft client id+secret required; tenant id optional —
// omit entirely for "common" multi-tenant which signs in any Microsoft account.
// Setting a stale/wrong tenant produces AADSTS90002 "Tenant not found" at first
// sign-in, which is harder to diagnose than just defaulting to common).
var microsoftClientId = builder.AddParameter("microsoft-client-id", secret: false);
var microsoftClientSecret = builder.AddParameter("microsoft-client-secret", secret: true);
var microsoftTenantIdValue = builder.Configuration["Parameters:microsoft-tenant-id"] ?? "";
IResourceBuilder<ParameterResource>? microsoftTenantId = string.IsNullOrEmpty(microsoftTenantIdValue)
    ? null : builder.AddParameter("microsoft-tenant-id", secret: false);

// Embedding, Google auth (non-secret optional — ACA accepts empty env vars,
// so a hard-coded empty default is fine for parameters that are only projected
// via WithEnvironment).
var embeddingEndpoint = builder.AddParameter("embedding-endpoint", value: "", secret: false);
var embeddingModel = builder.AddParameter("embedding-model", value: "", secret: false);
var googleClientId = builder.AddParameter("google-client-id", value: "", secret: false);

// LLM endpoints — sourced from secrets/env, never hardcoded. The Anthropic
// endpoint serves Claude on Azure Foundry (path /anthropic/); the Foundry
// endpoint serves OpenAI/Mistral/etc. via the multi-model /models path.
// Model names are configured per-tier below — also via parameters, never
// inlined here. Configure with `dotnet user-secrets set "Parameters:anthropic-endpoint" "https://..."`
// in dev, or via GitHub Actions / ACA env in deploy.
//
// 🚨 NO `value:` argument here either — same trap as the model-tier params
// (see comment below). `value: ""` makes Aspire resolve the param to empty
// string and skip user-secrets, leaving Anthropic__Endpoint blank in the
// portal — the AzureClaude factory then errors with "Endpoint is missing
// for model 'X'" even when user-secrets has Parameters:anthropic-endpoint set.
var anthropicEndpoint = builder.AddParameter("anthropic-endpoint", secret: false);
// azure-foundry-endpoint is OPTIONAL — defaulted in appsettings.json to the
// shared s-meshweaver `/models` path. user-secrets / env vars / deployment
// state files all override (standard IConfiguration order). The appsettings
// default avoids the `value: ""` trap above by going through the normal config
// pipeline instead of short-circuiting Aspire's parameter resolution.
var azureFoundryEndpoint = builder.AddParameter("azure-foundry-endpoint", secret: false);

// Anthropic model CATALOG: the concrete model names offered in the chat composer's
// model picker (Anthropic__Models__0/1/2 → BuiltInLanguageModelProvider). Model TIERS
// (heavy/standard/light) are removed — the active model is always the composer
// selection, never a tier. Hidden from source so the deployment owns the model identity.
//
// 🚨 NO `value:` argument: passing `value: ""` makes Aspire treat the param as resolved
// to the literal empty string and SKIP user-secrets / config lookup entirely, leaving the
// catalog empty and the chat dropdown with zero models. Without `value:`, Aspire reads
// from `Parameters:anthropic-model-{n}` (user-secrets locally, container env in deploy).
var anthropicModel0 = builder.AddParameter("anthropic-model-0", secret: false);
var anthropicModel1 = builder.AddParameter("anthropic-model-1", secret: false);
var anthropicModel2 = builder.AddParameter("anthropic-model-2", secret: false);

// Provider-key encryption master key (Ai:KeyProtection:MasterKey). Encrypts the
// literal ApiKey stored on ModelProvider nodes at rest so a Postgres/backup leak
// alone yields no usable key. Read config/user-secrets first; fall back to a
// clearly-dev default so local dev encrypts out of the box. test/prod MUST
// override via `Parameters:key-protection-master-key` (user-secrets / GitHub
// secret) — the dev default below is NOT secret and must never protect real keys.
// (Manual config read + non-empty value avoids the `value: ""` user-secrets-skip
// trap documented on the model-tier params above.)
var masterKeyValue = builder.Configuration["Parameters:key-protection-master-key"];
if (string.IsNullOrEmpty(masterKeyValue))
    masterKeyValue = "meshweaver-dev-key-protection-master-do-not-use-in-prod";
var keyProtectionMasterKey = builder.AddParameter("key-protection-master-key", secret: true, value: masterKeyValue);

// Optional secrets/params: ACA rejects secrets with empty values; ConfigureCustomDomain
// rejects empty hostnames. Read actual config values to guard optional registrations.
var embeddingKeyValue = builder.Configuration["Parameters:embedding-key"] ?? "";
var googleClientSecretValue = builder.Configuration["Parameters:google-client-secret"] ?? "";
var linkedinClientSecretValue = builder.Configuration["Parameters:linkedin-client-secret"] ?? "";
var customDomainValue = builder.Configuration["Parameters:custom-domain"] ?? "";
var certificateNameValue = builder.Configuration["Parameters:certificate-name"] ?? "";

// Custom domain + cert: register parameters only when config has real values.
// A hard-coded `value: ""` default would override user-secrets and ship an empty
// hostname into the bicep template, which ACA rejects with `InvalidHostName`.
IResourceBuilder<ParameterResource>? customDomain = string.IsNullOrEmpty(customDomainValue)
    ? null : builder.AddParameter("custom-domain", secret: false);
IResourceBuilder<ParameterResource>? certificateName = string.IsNullOrEmpty(certificateNameValue)
    ? null : builder.AddParameter("certificate-name", secret: false);
IResourceBuilder<ParameterResource>? embeddingKey = string.IsNullOrEmpty(embeddingKeyValue)
    ? null : builder.AddParameter("embedding-key", secret: true);
IResourceBuilder<ParameterResource>? googleClientSecret = string.IsNullOrEmpty(googleClientSecretValue)
    ? null : builder.AddParameter("google-client-secret", secret: true);

// LinkedIn OAuth app — serves both sign-in (Sign In with LinkedIn using
// OpenID Connect) and publishing posts on behalf of the signed-in user.
// The same app id is projected as `Authentication__LinkedIn__ClientId` for
// the auth pipeline and as `Social__LinkedIn__ClientId` for publishing.
// Client Id is public (shown on the consent screen URL) so it's inlined.
// The secret is wrapped as an AddParameter so Aspire resolves it at deploy
// time from user-secrets / GitHub Actions secrets and projects it into the
// container as a proper secret reference — a plain `builder.Configuration[...]`
// read was silently losing the value in prod (the env var was shipped empty
// and LinkedIn rejected token exchange with "client_secret missing").
//   dotnet user-secrets set "Parameters:linkedin-client-secret" "<value>" --project memex/aspire/Memex.AppHost
const string LinkedInClientId = "780dsuvyxglmc4";
IResourceBuilder<ParameterResource>? linkedinClientSecret = string.IsNullOrEmpty(linkedinClientSecretValue)
    ? null : builder.AddParameter("linkedin-client-secret", secret: true);

// --- Infrastructure axes ---
var isDeployed = mode is "test" or "prod";
var useLocalDb = mode == "local";

// --- ACA Environment (Sweden Central) ---
if (isDeployed)
{
    builder.AddAzureContainerAppEnvironment("memex-aca")
        .ConfigureInfrastructure(infra =>
        {
            var env = infra.GetProvisionableResources()
                .OfType<Azure.Provisioning.AppContainers.ContainerAppManagedEnvironment>()
                .Single();
            env.Location = new Azure.Core.AzureLocation("swedencentral");
        });
}

// --- Orleans (ephemeral, fresh cluster on each restart) ---
var orleansStorage = builder.AddAzureStorage("orleansstorage");
if (!isDeployed && builder.Environment.IsDevelopment())
{
    orleansStorage = orleansStorage.RunAsEmulator();
}
else if (isDeployed)
{
    orleansStorage = orleansStorage.ConfigureInfrastructure(infra =>
    {
        var storageAccount = infra.GetProvisionableResources()
            .OfType<Azure.Provisioning.Storage.StorageAccount>()
            .Single();
        storageAccount.Location = new Azure.Core.AzureLocation("swedencentral");
    });
}
var orleansTables = orleansStorage.AddTables("orleans-clustering");

var orleans = builder.AddOrleans("memex-mesh")
    .WithClustering(orleansTables);

// --- Application Insights (skipped in pure local mode — no Azure subscription needed) ---
var appInsights = useLocalDb
    ? null
    : builder.AddAzureApplicationInsights("appinsights")
        .ConfigureInfrastructure(infra =>
        {
            var component = infra.GetProvisionableResources()
                .OfType<Azure.Provisioning.ApplicationInsights.ApplicationInsightsComponent>()
                .Single();
            component.Location = new Azure.Core.AzureLocation("swedencentral");
        });

// --- Database Migration ---
var dbMigration = builder
    .AddProject<Projects.Memex_Database_Migration>("db-migration")
    .WithEnvironment("Embedding__Endpoint", embeddingEndpoint)
    .WithEnvironment("Embedding__Model", embeddingModel);

// Embedding API key is a secret — only set when configured (ACA rejects empty secrets).
// Without it the documentation backfill still runs; docs are full-text searchable, just
// not vector-indexed.
if (embeddingKey is not null)
    dbMigration.WithEnvironment("Embedding__ApiKey", embeddingKey);

if (appInsights is not null)
{
    dbMigration.WithReference(appInsights).WaitFor(appInsights);
}

// --- Portal (co-hosted Orleans silo + web) ---
var portal = builder
    .AddProject<Projects.Memex_Portal_Distributed>(isDeployed ? $"memex-{mode}" : "memex-local")
    .WithExternalHttpEndpoints()
    .WithReference(orleans)
    // Local modes need Development environment for static web assets (_framework, _content)
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", isDeployed ? "Production" : "Development")
    // Static-repo → DB sync: materialize the embedded docs, built-in agents, and model catalog
    // into their DB partitions on boot (served from PG — the distributed/Orleans routing does not
    // consult the in-memory embedded adapter, so without this /Doc pages hang). Mirrors the Helm
    // default and values.atioz.yaml.
    .WithEnvironment("Features__StaticRepoSync__Partitions__0", "Doc")
    .WithEnvironment("Features__StaticRepoSync__Partitions__1", "Agent")
    .WithEnvironment("Features__StaticRepoSync__Partitions__2", "Model")
    // Embedding
    .WithEnvironment("Embedding__Endpoint", embeddingEndpoint)
    .WithEnvironment("Embedding__Model", embeddingModel)
    // LLM: Anthropic (Azure Foundry Claude). Endpoint + model identities all
    // come from parameters — no URLs and no model names hardcoded here.
    // Agents declare PreferredModel in their MeshNode; ModelTier resolves via
    // the parameters below.
    .WithEnvironment("Anthropic__Endpoint", anthropicEndpoint)
    .WithEnvironment("Anthropic__ApiKey", azureFoundryKey)
    .WithEnvironment("Anthropic__Order", "1")
    // Advertise the deployed Claude catalog so the factory's Models[] is
    // non-empty — that's what BuiltInLanguageModelProvider scans to seed
    // the `nodeType:LanguageModel` mesh nodes under `Model/<id>`. Without
    // these the picker lists nothing for Anthropic and `claude-sonnet-4-6`
    // doesn't appear in autocomplete. These params are the model CATALOG (the
    // selectable models in the chat composer) — model tiers were removed; the
    // active model is always the composer selection.
    .WithEnvironment("Anthropic__Models__0", anthropicModel0)
    .WithEnvironment("Anthropic__Models__1", anthropicModel1)
    .WithEnvironment("Anthropic__Models__2", anthropicModel2)
    // Provider-key encryption master key (ConfigMasterKeyProvider reads this).
    .WithEnvironment("Ai__KeyProtection__MasterKey", keyProtectionMasterKey)
    // LLM: Azure AI Foundry (multi-model inference endpoint — covers OpenAI,
    // Mistral, DeepSeek, etc. through one endpoint).
    .WithEnvironment("AzureAIS__Endpoint", azureFoundryEndpoint)
    .WithEnvironment("AzureAIS__ApiKey", azureFoundryKey)
    .WithEnvironment("AzureAIS__Order", "0")
    // Authentication
    .WithEnvironment("Authentication__EnableDevLogin", mode != "prod" ? "true" : "false")
    .WithEnvironment("Authentication__Microsoft__ClientId", microsoftClientId)
    .WithEnvironment("Authentication__Microsoft__ClientSecret", microsoftClientSecret)
    .WithEnvironment("Authentication__Google__ClientId", googleClientId)
    .WithEnvironment("Authentication__LinkedIn__ClientId", LinkedInClientId)
    // NuGet cache for #r "nuget:..." directives (in-process restore via MeshWeaver.NuGet).
    .WithEnvironment("NUGET_PACKAGES", "/tmp/nuget-cache")
    // Wait for dependencies
    .WaitFor(orleansTables)
    .WaitForCompletion(dbMigration)
    // ACA deployment: sticky sessions (Blazor Server) + custom domain + resources
    .PublishAsAzureContainerApp((module, app) =>
    {
        app.Configuration.Ingress.StickySessionsAffinity = StickySessionAffinity.Sticky;
        if (customDomain is not null && certificateName is not null)
            app.ConfigureCustomDomain(customDomain, certificateName);

        // Scale: min 2 replicas (Orleans needs ≥2 for resilience), max 6 under load.
        // Each replica: 2 vCPU / 4Gi (50% of Consumption tier max 4 vCPU / 8Gi).
        app.Template.Scale.MinReplicas = 2;
        app.Template.Scale.MaxReplicas = 6;
        // Orleans needs time to drain grain activations to the surviving silo
        // before the container is killed.  Default ACA grace period is 30 s —
        // far too short for a clean Orleans handoff.  Set to 120 s so the
        // .NET host's 90 s ShutdownTimeout (set in Memex.Portal.Distributed)
        // completes before SIGKILL arrives.
        app.Template.TerminationGracePeriodSeconds = 120;
    });

// --- Claude Code co-hosting (Phase 5b) — opt-in feature flag ---
// Claude Code runs IN-PROCESS in the portal: the CLI is spawned per chat, each
// under the calling user's own CLAUDE_CONFIG_DIR + subscription token (so
// concurrent users on a replica never share credentials). Enabled at deploy via
// `Parameters:enable-claude-code=true`. When on, the portal:
//   • mounts the per-user `.claude` share at /mnt/users, and
//   • learns the mount root via ClaudeCode__ConfigDirRoot.
//
// 🚨 DEPLOY CHOICES gated by this flag (not compile-checkable here):
//   1. PORTAL IMAGE must bundle node + BOTH co-hosted CLIs: the Claude Code CLI
//      (@anthropic-ai/claude-code) AND the GitHub Copilot CLI. The portal is
//      AddProject, so select the CLI-enabled image at deploy via the portal's
//      <ContainerBaseImage> (or a portal Dockerfile variant) — toggled by the
//      same flag in the deploy pipeline.
//   2. STORAGE for /mnt/users must be durable + cross-replica. `WithVolume` below
//      is auto-translated by Aspire 13.x into an *Aspire-managed* Azure Files
//      share. To bring YOUR OWN account, attach a
//      ContainerAppManagedEnvironmentStorage (AzureFile: account+key from
//      Parameters:claude-storage-account / claude-storage-key, ShareName,
//      AccessMode=ReadWrite) to the `memex-aca` environment and reference it from
//      the portal's `.PublishAsAzureContainerApp` volume + volumeMount.
var enableClaudeCode = (builder.Configuration["Parameters:enable-claude-code"] ?? "false")
    .Equals("true", StringComparison.OrdinalIgnoreCase);
if (enableClaudeCode)
{
    // App-level wiring: tell the co-hosted client where per-user .claude lives.
    portal.WithEnvironment("ClaudeCode__ConfigDirRoot", "/mnt/users");
    // 🚨 The /mnt/users MOUNT itself can't use container `WithVolume` here — the
    // portal is AddProject (a ProjectResource), not a ContainerResource. Mount it
    // at the ACA layer inside the portal's existing `.PublishAsAzureContainerApp(
    // (module, app) => { … })` block: add an Azure Files volume to
    // `app.Template.Volumes` + a `VolumeMount` at /mnt/users on the container,
    // backed by a ContainerAppManagedEnvironmentStorage on `memex-aca` (BYO
    // account+key from Parameters:claude-storage-account / claude-storage-key).
    // Left for the deploy pass — needs a publish/deploy to finalize + verify.
}

// Optional secrets: only add as env vars when configured (ACA rejects empty secrets)
if (embeddingKey is not null)
    portal.WithEnvironment("Embedding__ApiKey", embeddingKey);
if (googleClientSecret is not null)
    portal.WithEnvironment("Authentication__Google__ClientSecret", googleClientSecret);
if (linkedinClientSecret is not null)
{
    // Same secret powers both sign-in and publishing flows.
    portal.WithEnvironment("Authentication__LinkedIn__ClientSecret", linkedinClientSecret);
    portal.WithEnvironment("Social__LinkedIn__ClientId", LinkedInClientId);
    portal.WithEnvironment("Social__LinkedIn__ClientSecret", linkedinClientSecret);
}

if (appInsights is not null)
    portal = portal.WithReference(appInsights);

// --- Azure Blob Storage ---
// Two blob containers share the `memexblobs` storage account:
//   `storage`         — content collections (files uploaded by users, article assets, etc.)
//   `nodetype-cache`  — content-addressed NodeType compiled assemblies (keyed by SHA-256
//                       of source + config + runtime), replacing the in-memory compile cache
//                       with a durable, cross-replica-consistent lookup.
if (useLocalDb)
{
    // Local emulated storage
    var contentStorage = builder.AddAzureStorage("memexblobs")
        .RunAsEmulator(
            azurite => azurite
                .WithDataBindMount("../../Azurite/Data")
                .WithLifetime(ContainerLifetime.Persistent)
                .WithExternalHttpEndpoints());
    var storageBlobs = contentStorage.AddBlobs("storage");
    var nodeTypeCache = contentStorage.AddBlobs("nodetype-cache");
    portal.WithReference(storageBlobs).WaitFor(storageBlobs);
    portal.WithReference(nodeTypeCache).WaitFor(nodeTypeCache);
}
else if (mode is "local-test" or "local-prod")
{
    // Connect to existing Azure Blob Storage via Azure Identity (az login, no secrets needed)
    var storageName = mode is "local-test" ? "meshweavermemextest" : "meshweavermemex";
    var contentStorage = builder.AddAzureStorage("memexblobs")
        .RunAsExisting(storageName, null);
    var storageBlobs = contentStorage.AddBlobs("storage");
    var nodeTypeCache = contentStorage.AddBlobs("nodetype-cache");
    portal.WithReference(storageBlobs);
    portal.WithReference(nodeTypeCache);
}
else
{
    // Deployed modes: provision Azure Blob Storage in Sweden Central
    var contentStorage = builder.AddAzureStorage("memexblobs")
        .ConfigureInfrastructure(infra =>
        {
            var storageAccount = infra.GetProvisionableResources()
                .OfType<Azure.Provisioning.Storage.StorageAccount>()
                .Single();
            storageAccount.Location = new Azure.Core.AzureLocation("swedencentral");
        });
    var storageBlobs = contentStorage.AddBlobs("storage");
    var nodeTypeCache = contentStorage.AddBlobs("nodetype-cache");
    portal.WithReference(storageBlobs).WaitFor(storageBlobs);
    portal.WithReference(nodeTypeCache).WaitFor(nodeTypeCache);
}

// --- PostgreSQL ---
if (useLocalDb)
{
    // Local Docker pgvector container
    var postgres = builder.AddPostgres("memex-postgres")
        .WithImage("pgvector/pgvector", "pg17")
        .WithDataVolume("memex-pgdata")
        .WithLifetime(ContainerLifetime.Persistent)
        .WithPgAdmin(pgAdmin => pgAdmin.WithLifetime(ContainerLifetime.Persistent));
    var db = postgres.AddDatabase("memex");

    dbMigration.WithReference(db).WaitFor(db);
    portal.WithReference(db).WaitFor(db);
}
else
{
    // Deployed modes: provision Azure PostgreSQL Flexible Server in Sweden Central
    var postgres = builder.AddAzurePostgresFlexibleServer("memex-postgres")
        .ConfigureInfrastructure(infra =>
        {
            var server = infra.GetProvisionableResources()
                .OfType<Azure.Provisioning.PostgreSql.PostgreSqlFlexibleServer>()
                .Single();
            server.Location = new Azure.Core.AzureLocation("swedencentral");
        });
    var dbName = mode is "test" ? "memex-test" : "memex";
    var db = postgres.AddDatabase("memex", databaseName: dbName);

    dbMigration.WithReference(db).WaitFor(db);
    portal.WithReference(db).WaitFor(db);
}

// Inject the portal's own external HTTPS endpoint as Mcp__BaseUrl so the
// MCP plugin doesn't have to fall back to its HttpContext probe (or, worse,
// a hard-coded localhost default). Aspire substitutes the actual allocated
// URL at container/process start — works the same in prod/test/local.
portal.WithEnvironment("Mcp__BaseUrl", portal.GetEndpoint("https"));

var app = builder.Build();
app.Run();
