using System.Security;
using System.Text;

namespace MeshWeaver.Plugin.Build;

/// <summary>
/// Writes the <c>.csproj</c> that builds one <see cref="PluginUnit"/> — the bridge between the
/// mesh's declarative <c>sources</c> and MSBuild.
/// </summary>
public static class ProjectEmitter
{
    /// <summary>
    /// Emits <c>&lt;unitName&gt;/&lt;unitName&gt;.csproj</c> under <paramref name="outputDirectory"/>
    /// and returns its path.
    /// </summary>
    /// <param name="unit">The unit to build.</param>
    /// <param name="frameworkVersion">MeshWeaver package version every reference is pinned to. This is
    /// the value that must also be stamped on the produced release, because it is what
    /// <c>HasUsableBuild</c> compares against at activation.</param>
    /// <param name="outputDirectory">Directory to write project folders into.</param>
    public static string Emit(PluginUnit unit, string frameworkVersion, string outputDirectory)
    {
        var projectDirectory = Path.Combine(outputDirectory, unit.UnitName);
        Directory.CreateDirectory(projectDirectory);

        var sb = new StringBuilder();
        sb.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        sb.AppendLine();
        sb.AppendLine($"  <!-- Generated by MeshWeaver.Plugin.Build for {SecurityElement.Escape(unit.NodePath)}.");
        sb.AppendLine("       Do not edit: the mesh node's `sources` are the source of truth. -->");
        sb.AppendLine();
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
        sb.AppendLine("    <Nullable>enable</Nullable>");
        // The unit supplies its own preamble (CompilationEnvironment.Usings); the SDK's implicit
        // set is a DIFFERENT list and layering both makes it unclear which one a symbol came from.
        sb.AppendLine("    <ImplicitUsings>disable</ImplicitUsings>");
        sb.AppendLine("    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>");
        sb.AppendLine("    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>");
        // One artifact instead of a DLL/PDB pair to keep in sync across package, blob store and
        // release record — and the symbols survive into production stack traces.
        sb.AppendLine("    <DebugType>embedded</DebugType>");
        sb.AppendLine($"    <AssemblyName>{SecurityElement.Escape(unit.UnitName)}</AssemblyName>");
        sb.AppendLine("    <RootNamespace></RootNamespace>");
        // In-mesh source is authored without XML docs; CS1591 would drown the real diagnostics.
        sb.AppendLine("    <NoWarn>$(NoWarn);CS1591</NoWarn>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine();

        sb.AppendLine("  <ItemGroup>");
        foreach (var directory in unit.Closure)
            sb.AppendLine($"    <Compile Include=\"{SecurityElement.Escape(directory)}/**/*.cs\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();

        sb.AppendLine("  <ItemGroup>");
        foreach (var @using in CompilationEnvironment.Usings)
            sb.AppendLine($"    <Using Include=\"{@using}\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();

        sb.AppendLine("  <ItemGroup>");
        foreach (var package in CompilationEnvironment.PackageIds)
            sb.AppendLine(
                $"    <PackageReference Include=\"{package}\" Version=\"{SecurityElement.Escape(frameworkVersion)}\" />");
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();
        sb.AppendLine("</Project>");

        var projectPath = Path.Combine(projectDirectory, unit.UnitName + ".csproj");
        File.WriteAllText(projectPath, sb.ToString());
        return projectPath;
    }
}
