using './frontend.module.bicep'

param azure_postgres_outputs_connectionstring = '{{ .Env.AZURE_POSTGRES_CONNECTIONSTRING }}'
param entraidclientid_value = '{{ parameter "EntraIdClientId" }}'
param entraidtenantid_value = '{{ parameter "EntraIdTenantId" }}'
param frontend_containerimage = '{{ .Image }}'
param frontend_containerport = '{{ targetPortOrDefault 8080 }}'
param mesh_cluster_id_value = '{{ parameter "mesh_cluster_id" }}'
param mesh_service_id_value = '{{ parameter "mesh_service_id" }}'
param meshweaverCertificate = '{{ parameter "meshweaverCertificate" }}'
param meshweaverDomain = '{{ parameter "meshweaverDomain" }}'
param meshweaverblobs_outputs_blobendpoint = '{{ .Env.MESHWEAVERBLOBS_BLOBENDPOINT }}'
param meshweaverblobs_outputs_tableendpoint = '{{ .Env.MESHWEAVERBLOBS_TABLEENDPOINT }}'
param outputs_azure_container_apps_environment_id = '{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param outputs_azure_container_registry_endpoint = '{{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param outputs_azure_container_registry_managed_identity_id = '{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param outputs_managed_identity_client_id = '{{ .Env.MANAGED_IDENTITY_CLIENT_ID }}'
param portaladmingroup_value = '{{ parameter "PortalAdminGroup" }}'
