---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "memex-portal-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "memex-portal"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__memex: "Host=memex-postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.memex_portal.memex_postgres_password }};Database=memex"
  MEMEX_PASSWORD: "{{ .Values.secrets.memex_portal.memex_postgres_password }}"
  MEMEX_URI: "postgresql://postgres:{{ .Values.secrets.memex_portal.memex_postgres_password }}@memex-postgres-service:5432/memex"
type: "Opaque"
