using System;
using System.Reactive;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading.Tasks;
using MeshWeaver.Data;
using MeshWeaver.Hosting.Monolith.TestBase;
using MeshWeaver.Mesh;
using MeshWeaver.Mesh.Services;
using MeshWeaver.Messaging;
using Xunit;

namespace MeshWeaver.Graph.Test;

/// <summary>The probe type's content — a trigger field and a state, the documented control-plane shape.</summary>
public record TriggerProbeContent
{
    /// <summary>The trigger the watcher reacts to. <c>"Go"</c> asks for a run.</summary>
    public string RequestedAction { get; init; } = "";

    /// <summary>Where the request is.</summary>
    public string State { get; init; } = "Proposed";
}

/// <summary>
/// The documented control-plane contract — <i>"State-machine semantics? Set a <c>RequestedX</c>
/// field and let the owning hub's watcher react"</i> — held at the ONE moment nothing else pins:
/// when the trigger is already on the node the API CREATES.
///
/// <para>🚨 Nothing else covers that moment, and its absence was read as a missing feature.
/// Systemorph/MeshWeaver.Plugins#1320 reported that an operation request filed through the API
/// "was created. It never previewed. steps: [] forever, no error, no log, nothing to grep", and
/// concluded that the executable half must be generated by the creation FLOW rather than by the
/// node's own watcher — i.e. that the API path had no watcher at all. Measured on a live portal on
/// 2026-09-06 it does: an API-created request started previewing 86 ms after the create. The real
/// defect was elsewhere (a watcher that could stop), but the contract asserted here had no test,
/// so "was it ever wired?" cost an afternoon of archaeology on production version history.</para>
///
/// <para>The watcher reports through an <see cref="AsyncSubject{T}"/> rather than by writing state
/// the test then reads back: reading the node's path opens a subscription to its per-node hub and
/// would ACTIVATE the very hub whose activation is what this measures.</para>
/// </summary>
public class ControlPlaneTriggerOnCreateTest(ITestOutputHelper output) : MonolithMeshTestBase(output)
{
    private const string ProbeType = "TriggerProbe";

    /// <summary>
    /// The watcher's own report that it RAN — a positive signal, reported from inside the per-node
    /// hub. Deliberately NOT observed by reading the node back: a read of the node's path opens a
    /// subscription to its per-node hub and would ACTIVATE the very hub whose activation is what
    /// this test measures. Instance field, never static.
    /// </summary>
    private readonly AsyncSubject<string> watcherRan = new();

    protected override MeshBuilder ConfigureMesh(MeshBuilder builder)
    {
        builder.AddMeshNodes(new MeshNode(ProbeType)
        {
            Name = "Trigger probe",
            HubConfiguration = config => config
                .WithContentType<TriggerProbeContent>()
                .WithInitialization(hub =>
                {
                    var workspace = hub.GetWorkspace();
                    hub.RegisterForDisposal(workspace.GetMeshNodeStream()
                        .Where(node => node is not null)
                        .Select(node => Process(hub, workspace, node!))
                        .Concat()
                        .Subscribe(_ => { }, _ => { }));
                }),
        });
        builder.ConfigureHub(config => config.WithType<TriggerProbeContent>(nameof(TriggerProbeContent)));
        return base.ConfigureMesh(builder);
    }

    /// <summary>One idempotent step: the trigger is consumed and the state advances — the Provision / OperationRequest shape.</summary>
    private IObservable<Unit> Process(IMessageHub hub, IWorkspace workspace, MeshNode node)
    {
        var content = node.ContentAs<TriggerProbeContent>(hub.JsonSerializerOptions);
        if (content is null || content.RequestedAction != "Go")
            return Observable.Empty<Unit>();
        watcherRan.OnNext(node.Path);
        watcherRan.OnCompleted();
        return workspace.GetMeshNodeStream(node.Path)
            .Update(live =>
            {
                var c = live.ContentAs<TriggerProbeContent>(hub.JsonSerializerOptions);
                return c is null
                    ? live
                    : live with { Content = c with { State = "Done", RequestedAction = "" } };
            })
            .Select(_ => Unit.Default);
    }

    private MeshNode Probe(string id, string action) =>
        new(id, TestPartition)
        {
            Name = id,
            NodeType = ProbeType,
            Content = new TriggerProbeContent { RequestedAction = action },
        };

    /// <summary>
    /// THE CONTROL. A node created with no trigger, then triggered by the canonical write, runs —
    /// so the watcher, the type registration and the reactive shape are all sound, and a failure of
    /// the sibling test below can only be about WHEN the trigger arrives.
    /// </summary>
    [Fact(Timeout = 120000)]
    public async Task ATriggerPatchedAfterCreate_RunsTheWatcher()
    {
        var id = "PatchProbe" + Guid.NewGuid().ToString("N")[..8];
        var path = $"{TestPartition}/{id}";

        await NodeFactory.CreateNode(Probe(id, action: "")).Take(1)
            .Should().Within(60.Seconds()).Emit("the probe node is created");

        await Mesh.GetWorkspace().GetMeshNodeStream(path)
            .Update(live =>
            {
                var c = live.ContentAs<TriggerProbeContent>(Mesh.JsonSerializerOptions);
                return c is null ? live : live with { Content = c with { RequestedAction = "Go" } };
            })
            .Should().Within(60.Seconds()).Emit("the canonical write lands");

        await watcherRan.Should().Within(60.Seconds())
            .Emit("a trigger set by a patch reaches the node's own control plane");
    }

    /// <summary>
    /// 🚨 THE ONE THAT WAS NOT PINNED. An agent files a request the way an agent actually can —
    /// ONE create, trigger already set, no page ever opened.
    ///
    /// <para><c>IMeshService.CreateNode</c> posts to the node-operation target, not to the new
    /// node's own address, so nothing here starts that hub on purpose; routing does it, and the
    /// watcher installed by the type's <c>WithInitialization</c> sees the trigger on its first
    /// emission. If this ever goes red, every control plane in the fleet — <c>Store/Provision</c>,
    /// <c>Store/Order</c>, <c>Essentials/OperationRequest</c> — silently stops answering the API,
    /// and the symptom is a node that reads as merely pending.</para>
    /// </summary>
    [Fact(Timeout = 120000)]
    public async Task ATriggerSetAtCreate_RunsTheWatcher()
    {
        var id = "CreateProbe" + Guid.NewGuid().ToString("N")[..8];

        await NodeFactory.CreateNode(Probe(id, action: "Go")).Take(1)
            .Should().Within(60.Seconds()).Emit("the probe node is created");

        await watcherRan.Should().Within(60.Seconds())
            .Emit("a request filed through the API must reach its own control plane");
    }
}
