// GENERATED by scripts/gen-deployment.mjs from deployment/default.json — do not edit.
// Regenerate: npm run gen:deployment (runs automatically before start/web:export).
// This file IS the deployment: the static imports below are how a deployment's client
// modules enter the bundle (Hermes loads no code at runtime — build-time composition).
import type { DeploymentModule } from "@meshweaver/react/core";

export interface DeploymentBranding {
  displayName: string;
  accent: string;
  accentDark: string;
}

export const deployment = {
  name: "Memex",
  portalUrl: "http://localhost:5250",
  branding: {
    displayName: "MeshWeaver",
    accent: "#0f6cbd",
    accentDark: "#4aa3e8",
  } satisfies DeploymentBranding,
  modules: [] as readonly DeploymentModule[],
} as const;
