// GENERATED by scripts/gen-deployment.mjs from deployment/default.json — do not edit.
// IMPORT-FREE on purpose: theme/shell read this without touching the module graph (no cycles).
export const deploymentBranding = {
  name: "Memex",
  portalUrl: "http://localhost:5250",
  displayName: "MeshWeaver",
  accent: "#0f6cbd",
  accentDark: "#4aa3e8",
} as const;
