---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "memex-postgres-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "memex-postgres"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.memex_postgres.memex_postgres_password }}"
type: "Opaque"
