using OpenSmc.Messaging;

namespace OpenSmc.Application;

public interface IViewModelAddress : IHostedAddress
{
    object ModelAddress { get; }
    MainLayoutAddress MainLayout { get; }
}

/// <summary>
/// </summary>
/// <param name="Id">Id is a guid generated by the client</param>
/// <param name="Host"> <see cref="ApplicationAddress"/> with Application Id and Project Id</param>
public record MainLayoutAddress(string Id, ApplicationAddress ApplicationAddress, object Host) : IHostedAddress
{
    public MainLayoutAddress(string Id, ApplicationAddress ApplicationAddress) : this(Id, ApplicationAddress, ApplicationAddress) {}

    public MainLayoutAddress() : this(null, null){}
}

public record ViewModelAddress<TModelAddress>(TModelAddress ModelHub, MainLayoutAddress MainLayout) : IViewModelAddress
where TModelAddress : IHostedAddress
{
    public IViewModelAddress SetMainLayout(MainLayoutAddress mainLayout) => this with { MainLayout = mainLayout };
    object IViewModelAddress.ModelAddress => ModelHub;
    object IHostedAddress.Host => ModelHub.Host;
}


public record ViewModelAddress(string Id, ApplicationAddress Application) : ApplicationHostedAddress(Application)
{
}