using System.Collections.Immutable;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace MeshWeaver.PluginCatalog;

/// <summary>
/// The CI-maintained per-plugin manifest sidecar (<c>&lt;Plugin&gt;/manifest.lock</c> in the plugins
/// repo): a per-file sha256 map plus an overall <see cref="ModuleVersion"/>, generated by
/// <c>scripts/gen-manifests.py</c> and verified by the plugins repo's CI. It lets a consumer know
/// IMMEDIATELY which nodes an update touches: the catalog compares <see cref="ModuleVersion"/>
/// against the installed record to skip a whole package, and <see cref="DiffFrom"/> yields the exact
/// changed/removed file set so only those nodes are fetched and upserted — unchanged nodes are never
/// read, never rewritten, never re-broadcast, and their NodeTypes never recompile.
///
/// <para>🚨 Hashes are compared MANIFEST-TO-MANIFEST only (the map stored on the install record vs
/// the new manifest) — never against any server-side node token. The hash algorithm is a generator
/// implementation detail; the consumer treats the values as opaque change tokens.</para>
/// </summary>
public sealed record ModuleManifest
{
    /// <summary>The manifest sidecar's file name inside a plugin folder.</summary>
    public const string FileName = "manifest.lock";

    /// <summary>The plugin folder name the manifest describes.</summary>
    public string Module { get; init; } = "";

    /// <summary>The overall module version — a hash over the sorted (path, file-hash) pairs.
    /// Equal versions ⇒ identical file set ⇒ nothing to sync.</summary>
    public string ModuleVersion { get; init; } = "";

    /// <summary>The git commit the manifest was generated at (traceability only — excluded from
    /// <see cref="ModuleVersion"/>).</summary>
    public string? SourceCommit { get; init; }

    /// <summary>Per-file change tokens: repo-relative path (plugin-folder-prefixed, POSIX) → sha256.</summary>
    public ImmutableSortedDictionary<string, string> Files { get; init; } =
        ImmutableSortedDictionary<string, string>.Empty;

    /// <summary>True when <paramref name="relativePath"/> is a plugin's manifest sidecar
    /// (<c>manifest.lock</c> at the folder root or any nesting).</summary>
    public static bool IsManifestPath(string relativePath) =>
        string.Equals(relativePath, FileName, StringComparison.OrdinalIgnoreCase)
        || relativePath.EndsWith("/" + FileName, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Parses a manifest.lock's JSON tolerantly: any malformed/incomplete input returns null (the
    /// caller falls back to the legacy full-install path) — a bad manifest must never wedge an
    /// install.
    /// </summary>
    public static ModuleManifest? TryParse(string json, ILogger? logger = null)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var r = doc.RootElement;
            if (r.ValueKind != JsonValueKind.Object
                || !r.TryGetProperty("moduleVersion", out var version)
                || version.ValueKind != JsonValueKind.String
                || string.IsNullOrEmpty(version.GetString())
                || !r.TryGetProperty("files", out var files)
                || files.ValueKind != JsonValueKind.Object)
                return null;
            var map = ImmutableSortedDictionary.CreateBuilder<string, string>(StringComparer.Ordinal);
            foreach (var prop in files.EnumerateObject())
            {
                if (prop.Value.ValueKind != JsonValueKind.String)
                    return null;
                map[prop.Name] = prop.Value.GetString()!;
            }
            return new ModuleManifest
            {
                Module = r.TryGetProperty("module", out var m) && m.ValueKind == JsonValueKind.String
                    ? m.GetString()! : "",
                ModuleVersion = version.GetString()!,
                SourceCommit = r.TryGetProperty("sourceCommit", out var c) && c.ValueKind == JsonValueKind.String
                    ? c.GetString() : null,
                Files = map.ToImmutable(),
            };
        }
        catch (JsonException ex)
        {
            logger?.LogWarning(ex, "manifest.lock is not valid JSON; falling back to full install.");
            return null;
        }
    }

    /// <summary>
    /// Diffs this (new) manifest against the file map recorded at the previous install: which files
    /// were added or changed (fetch + upsert those) and which were removed (prune their nodes). A
    /// null/empty <paramref name="previousFiles"/> means no baseline — every file counts as changed.
    /// </summary>
    public ManifestDelta DiffFrom(IReadOnlyDictionary<string, string>? previousFiles)
    {
        if (previousFiles is null || previousFiles.Count == 0)
            return new ManifestDelta(Files.Keys.ToImmutableSortedSet(StringComparer.Ordinal),
                ImmutableSortedSet<string>.Empty);
        var changed = Files
            .Where(kv => !previousFiles.TryGetValue(kv.Key, out var prev)
                         || !string.Equals(prev, kv.Value, StringComparison.Ordinal))
            .Select(kv => kv.Key)
            .ToImmutableSortedSet(StringComparer.Ordinal);
        var removed = previousFiles.Keys
            .Where(k => !Files.ContainsKey(k))
            .ToImmutableSortedSet(StringComparer.Ordinal);
        return new ManifestDelta(changed, removed);
    }
}

/// <summary>The file-level difference between two manifests: what to fetch/upsert and what to prune.</summary>
/// <param name="AddedOrChangedFiles">Repo-relative paths new or changed since the baseline.</param>
/// <param name="RemovedFiles">Repo-relative paths present in the baseline but gone now.</param>
public sealed record ManifestDelta(
    ImmutableSortedSet<string> AddedOrChangedFiles,
    ImmutableSortedSet<string> RemovedFiles)
{
    /// <summary>True when the manifests describe an identical file set.</summary>
    public bool IsEmpty => AddedOrChangedFiles.Count == 0 && RemovedFiles.Count == 0;
}
