name: Publish NuGet Packages

on:
  push:
    tags:
      - 'bl*.*.*'

permissions:
  contents: read
  packages: write
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
    - name: Restore workloads
      run: dotnet workload restore
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore 

    - name: Pack NuGet packages
      run: dotnet pack --configuration Release --no-build --output ./nupkgs  /bl:msbuild.binlog

    - name: Upload binlog
      uses: actions/upload-artifact@v4
      with:
        name: msbuild-binlog
        path: msbuild.binlog
